version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: nemogym_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gym_db
      MYSQL_USER: gym_user
      MYSQL_PASSWORD: gym_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: