
spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/gym_db
spring.datasource.username=gym_user
spring.datasource.password=gym_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mi-clave-452777-Kpo-super-secreta

logging.level.org.springframework.security=DEBUG



mercadopago.access-token=APP_USR-680092415268059-030509-242f0b00713411010a0bd4fa5cc5467c-2132796369
app.webhook-url=https://7b07-152-170-28-108.ngrok-free.app
app.frontend-url=https://e313-152-170-28-108.ngrok-free.app
app.cors-origin=https://79ee-152-170-28-108.ngrok-free.app

management.endpoints.web.exposure.include=mappings
management.endpoint.mappings.access=unrestricted


logging.file.name=logs/nemogym.log
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5p) %clr(---){faint} %m%n-
logging.level.root=WARN
logging.level.com.nemogym.backend=INFO
logging.level.org.hibernate.SQL=WARN